[package]
name = "mini-toolbelt"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "1.5.6"
aws-sdk-sqs = "1.42.0"
clap = { version = "4.5.17", features = ["derive"] }
tokio = { version = "1.40.0", features = ["full"] }
